# Generated by Django 3.0.3 on 2020-05-23 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.TextField()),
                ('comment_id', models.TextField()),
                ('text', models.TextField()),
                ('date', models.DateTimeField()),
                ('author', models.TextField()),
                ('author_channel_url', models.URLField()),
                ('like_count', models.IntegerField()),
                ('replies_count', models.IntegerField()),
                ('has_sensitive_content', models.BooleanField(default=False)),
                ('senstivite_info', models.TextField(default=None)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('sentiment_stat', models.TextField(default=None)),
                ('lang', models.CharField(default='en', max_length=10)),
                ('isSpam', models.BooleanField(default=False)),
                ('hateType', models.TextField(default='neutral')),
            ],
        ),
        migrations.CreateModel(
            name='videoInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelId', models.TextField()),
                ('channelIdTitle', models.TextField()),
                ('videoId', models.TextField()),
                ('videoUrl', models.TextField(default='https://www.youtube.com')),
                ('name', models.TextField()),
                ('description', models.TextField()),
                ('thumbnail', models.TextField()),
                ('viewsCount', models.IntegerField(default=0)),
                ('likeCount', models.IntegerField(default=0)),
                ('dislikeCount', models.IntegerField(default=0)),
                ('favouriteCount', models.IntegerField(default=0)),
                ('commentCount', models.IntegerField(default=0)),
            ],
        ),
    ]
