# Generated by Django 3.0.3 on 2020-05-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComDisp', '0003_videoinfo_videoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='isSpam',
            field=models.BooleanField(default=False),
        ),
    ]
