# Generated by Django 3.0.3 on 2020-05-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ComDisp', '0004_comment_isspam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
